### ISSUE TITLE
割り算が動かない

### ISSUE THREAD

**Issue by t4ni-XP** [fujimaki3968/enpit-git-practice-teamC#1]
## 操作手順
* プルダウンを割り算の記号にしたら
* 掛け算の計算が表示された

## 本来の想定
* プルダウンを割り算の記号にしたら
* 割り算が計算されてほしい

## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン

**Comment by fujimaki3968** [comment]
#10
