### ISSUE TITLE
小数点以下切り上げの動作

### ISSUE THREAD

**Issue by t4ni-XP** [fujimaki3968/enpit-git-practice-teamC#3]
## 操作手順
* 小数点以下切り上げを選択したら
* 小数点以下が切り捨てられた

## 本来の想定
* 小数点以下切り上げを選択したら
* 小数点以下を切り上げたい

## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン

**Comment by fujimaki3968** [comment]
#4 
すでに修正ずみ
