### ISSUE TITLE
takeda

### ISSUE THREAD

**Issue by tk800000000** [fujimaki3968/enpit-git-practice-teamC#5]
## 操作手順
*-1+-2したら
* 3になった
* -1+2=-1
* 1+-2=3
* 1+0.5=1.5
* -2/100=200
## 本来の想定
* 〜したら
* 〜になってほしい

## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン

**Comment by fujimaki3968** [comment]
#7
