### ISSUE TITLE
1つ目の項目がマイナスだと計算されない

### ISSUE THREAD

**Issue by t4ni-XP** [fujimaki3968/enpit-git-practice-teamC#8]
## 操作手順
* 1つ目の項目にマイナスの数値を入れて足し算をすると
* 1つ目の項目がプラスの数値のときの計算結果が出力された

## 本来の想定
* 1つ目の項目にマイナスの数値を入れて足し算をすると
* 正常な数値が出力される

## 操作環境
* OS
* OSバージョン
* ブラウザ
* ブラウザバージョン

**Comment by tk800000000** [comment]
おｋ
